[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://cdn.jsdelivr.net; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data:; font-src 'self' data: https://cdn.jsdelivr.net;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_API_URL = "https://api.example.com"
  VITE_APP_ENV = "production"
  VITE_SENTRY_DSN = "your-sentry-dsn"
  VITE_GA_TRACKING_ID = "your-ga-tracking-id"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[build.hooks]
  preBuild = "cd functions && npm install && cd .."
  postBuild = "npm run build"

[[plugins]]
  package = "@netlify/plugin-image-optim"
  [plugins.inputs]
    quality = 80
    maxWidth = 1920
    maxHeight = 1080

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    threshold = 0.8

[[plugins]]
  package = "@netlify/plugin-functions"
  [plugins.inputs]
    functions = "functions"

[build.processing]
  skip_processing = false
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  html = { pretty_urls = true }
  images = { compress = true }
